### ISSUE TITLE
Error invoking Method 'cart/submitPayment': Access Denied [403]

### ISSUE THREAD

**Issue by valorloff** [reactioncommerce/reaction-paymentmethod#7] opened 2016-06-17 16:31 UTC
testing in fresh just installed RC lead to the same:
Error invoking Method 'cart/submitPayment': Access Denied [403], 
which is appears after submit order

**Comment by zenweasel** [comment] 2016-06-18 02:09
Duplicate of https://github.com/reactioncommerce/reaction/issues/1036

**Closed by zenweasel** 2016-06-18 02:09 UTC
Labels: duplicate
